require("nvim-treesitter").install({
	"typescript",
	"javascript",
	"json",
	"markdown",
	"lua",
	"luadoc",
	"dot",
	"dockerfile",
	"jsx",
	"git_config",
	"git_rebase",
	"gitattributes",
	"gitcommit",
	"gitignore",
	"gomod",
	"gosum",
	"gotmpl",
	"gowork",
	"graphql",
	"html",
	"tsx",
	"vim",
	"vimdoc",
	"yaml",
	"zsh",
})
vim.api.nvim_create_autocmd("FileType", {
	pattern = {
		"typescript",
		"javascript",
		"json",
		"markdown",
		"lua",
		"luadoc",
		"nginx",
		"dot",
		"dockerfile",
		"jsx",
		"git_config",
		"git_rebase",
		"gitattributes",
		"gitcommit",
		"gitignore",
		"html",
		"tsx",
		"vim",
		"vimdoc",
		"yaml",
		"zsh",
		"ts",
		"tsx",
		"jsx",
		"ts",
	},
	callback = function(args)
		vim.treesitter.start(args.buf)
		-- vim.wo[0][0].foldexpr = 'v:lua.vim.treesitter.foldexpr()'
		-- vim.wo[0][0].foldmethod = 'expr'
		--- vim.bo.indentexpr = "v:lua.require'nvim-treesitter'.indentexpr()"
		return true
	end,
})
